class Gemini:
    """
    Handles API for Gemini.

    Attributes:
        ai_model: API for Gemini.
    """

    def __init__(self, ai_model):
        self.__ai_model = ai_model

    def get_response(self, prompt: str) -> str:
        """
        Returns a response to the given prompt generated by Gemini. This method allows
        only stateless conversation, meaning Gemini will not remember your previous
        queries.
        """
        response = self.__ai_model.generate_content(prompt)
        return response.text
