name: Format with black

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Black formatter
        uses: psf/black@stable
        with:
          options: "."

      - name: Commit formatted code
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Autoformat code with Black"
            git push
          else
            echo "No changes detected"
          fi
