name: Build Docker Images

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build -f backend/Dockerfile -t future-customer-backend:latest backend/

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build frontend image
        run: |
          docker build -f frontend/Dockerfile -t future-customer-frontend:latest frontend/
